pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo "Deploy da Vinheria"
            }
        }

        stage('Deploy') {
            steps {
                script {
                    // pasta de publicação (deploy)
                    def publishDir = 'C:\\deploy-vinheria'

                    // cria a pasta se não existir
                    bat """
                    if not exist "${publishDir}" (
                        mkdir "${publishDir}"
                    )
                    """

                    // copia tudo que está no workspace do Jenkins (seu repo) para a pasta de deploy
                    bat """
                    xcopy "%WORKSPACE%\\*" "${publishDir}\\" /E /Y /I
                    """
                }
            }
        }
    }
}

